#!/usr/bin/env bash
set -e

target="$1"
s3_bucket="$2"

# Copy the pub/ directory into the S3 bucket specified

# Do CSS files first with forced mime (mime-magic guesses this incorrectly)
# Don't need cache control header since we're adding a cache-buster hash to
# each CSS file
(cd $target && \
    s3cmd put \
      --mime-type=text/css \
      --exclude="*" \
      --include="*.css" \
      --recursive * s3://$s3_bucket )

# # Do SVG files next with forced mime (mime-magic guesses this incorrectly)
(cd $target && \
    s3cmd put \
      --mime-type=image/svg+xml \
      --exclude="*" \
      --include="*.svg" \
      --recursive * s3://$s3_bucket )

# Next do any other file with an extension and use guessed mime. These files
# shouldn't change much (or have a hash), so no need for header. Exclude
# blanks because these need to update right away to point to the correct
# versions of different files.
(cd $target && \
    s3cmd put \
      --guess-mime-type \
      --exclude="*.css" \
      --exclude="*.svg" \
      --exclude="*.html" \
      --rexclude="^[^\\.]+$" \
      --recursive * s3://$s3_bucket )

# Do remainder with guessed mime, defaulting to HTML (because of blanks)
(cd $target && \
    s3cmd put \
      --exclude="*.*" \
      --include="*.html" \
      --mime-type=text/html \
      --add-header="Cache-Control:max-age=60" \
      --recursive * s3://$s3_bucket )
