#!/usr/bin/env bash
set -e

target="$1"
s3_bucket="$2"

# Copy the pub/ directory into the S3 bucket specified

# Do CSS files first with forced mime (mime-magic guesses this incorrectly)
# Don't need cache control header since we're adding a cache-buster hash to
# each CSS file
(cd $target && \
    s3cmd put \
      --mime-type=text/css \
      --exclude="*" \
      --include="*.css" \
      --add-header="Cache-Control:max-age=2592000" \
      --recursive * s3://$s3_bucket )

# # Do SVG files next with forced mime (mime-magic guesses this incorrectly)
(cd $target && \
    s3cmd put \
      --mime-type=image/svg+xml \
      --exclude="*" \
      --include="*.svg" \
      --add-header="Cache-Control:max-age=2592000" \
      --recursive * s3://$s3_bucket )

# Do any remaining files with extensions with guessed mime.
# Ignore stats.json (revision control only).
# Ignore HTML (see below).
(cd $target && \
    s3cmd put \
      --guess-mime-type \
      --exclude="*.css" \
      --exclude="*.svg" \
      --exclude="stats.json" \
      --exclude="*.html" \
      --rexclude="^[^\.]+$" \
      --add-header="Cache-Control:max-age=2592000" \
      --recursive * s3://$s3_bucket )

# Do top-level files, defaulting to HTML (because of blanks). Use shorter cache
# control with HTML files so updated HTML loads new JS / CSS.
(cd $target && \
    s3cmd put \
      --guess-mime-type \
      --exclude="*" \
      --rinclude="^[^\.]+$" \
      --include="*.html" \
      --default-mime-type=text/html \
      --add-header="Cache-Control:max-age=60" \
      --recursive * s3://$s3_bucket )